In [1]:
import numpy as np
# ベクトルの定義
a = np.array([1, 2, 3])

a.shape
a.ndim

1

In [2]:
# 行列の定義
b = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
print('Shape:', b.shape)
print('Rank:', b.ndim)

Shape: (3, 3)
Rank: 2


In [4]:
a = np.zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
from sklearn.datasets import load_boston

dataset = load_boston()

/Users/higuchitomoya/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the C

In [6]:
x = dataset.data
t = dataset.target
x.shape

(506, 13)

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.3, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression

# モデルの定義
reg_model = LinearRegression()

In [9]:
# モデルの訓練
reg_model.fit(x_train, t_train)

LinearRegression()

In [10]:
reg_model.coef_

array([-1.21310401e-01,  4.44664254e-02,  1.13416945e-02,  2.51124642e+00,
       -1.62312529e+01,  3.85906801e+00, -9.98516565e-03, -1.50026956e+00,
        2.42143466e-01, -1.10716124e-02, -1.01775264e+00,  6.81446545e-03,
       -4.86738066e-01])

In [11]:
# 訓練後のバイアス b
reg_model.intercept_

37.937107741832556

In [12]:
reg_model.score(x_train, t_train)

0.7645451026942549

In [13]:
reg_model.predict(x_test[:1])

array([24.9357079])

In [14]:
reg_model.score(x_test, t_test)


0.6733825506400196